In [22]:
import pandas as pd
import numpy as np

employments=pd.read_csv('/Users/alexfion/Dropbox/Alex/dataViz/AShymanskaya.github.io/portfolio/visualizations/pacific_dataviz/full_story/data/employment.csv')
agricultural_land=pd.read_csv('/Users/alexfion/Dropbox/Alex/dataViz/AShymanskaya.github.io/portfolio/visualizations/pacific_dataviz/full_story/data/agricultural_land.csv')
food_security=pd.read_csv('/Users/alexfion/Dropbox/Alex/dataViz/AShymanskaya.github.io/portfolio/visualizations/pacific_dataviz/full_story/data/food_insecurity.csv')[['GEO_PICT','OBS_VALUE']].rename(columns={'OBS_VALUE':'food_insecurity'})
fishing=pd.read_csv('/Users/alexfion/Dropbox/Alex/dataViz/AShymanskaya.github.io/portfolio/visualizations/pacific_dataviz/full_story/data/fishing_total.csv')[['GEO_PICT','OBS_VALUE']].rename(columns={'OBS_VALUE':'fishing_families'})

In [24]:
fishing.fishing_families.mean()

24.3

In [2]:
employment_last_time = employments[employments['Indicator']=='Employment in agriculture (% of total employment) (modeled ILO estimate)'][['GEO_PICT','TIME_PERIOD','OBS_VALUE']].groupby('GEO_PICT').last().reset_index().drop(columns='TIME_PERIOD').rename(columns={'OBS_VALUE':'employment_agriculture'})

value_last_time = employments[employments['Indicator']=='Agriculture value added (% of GDP)'][['GEO_PICT','TIME_PERIOD','OBS_VALUE']].groupby('GEO_PICT').last().reset_index().drop(columns='TIME_PERIOD').rename(columns={'OBS_VALUE':'agriculture_value_added'})

agricultural_land_last_time = agricultural_land[['GEO_PICT','TIME_PERIOD','OBS_VALUE','Pacific Island Countries and territories']].groupby('GEO_PICT').last().reset_index().drop(columns='TIME_PERIOD').rename(columns={'OBS_VALUE':'agricultural_land'})

In [15]:
fishing

  GEO_PICT  fishing_families
0       TO                10
1       TK                24
2       CK                25
3       PW                10
4       NR                14
5       MH                15
6       TV                53
7       KI                44
8       VU                31
9       NU                17

In [3]:
employment_last_time

  GEO_PICT  employment_agriculture
0       FJ                   28.80
1       GU                    0.24
2       NC                    1.82
3       PF                    2.11
4       PG                   18.48
5       SB                   37.29
6       TO                   26.94
7       VU                   42.35
8       WS                   20.14

In [4]:
value_last_time

   GEO_PICT  agriculture_value_added
0        FJ                     8.29
1        FM                    22.47
2        KI                    23.09
3        MH                    20.63
4        NC                     1.79
5        PF                     2.25
6        PG                    16.93
7        PW                     3.41
8        SB                    33.76
9        TO                    16.32
10       VU                    21.22
11       WS                    11.02

In [5]:
food_security

  GEO_PICT  food_insecurity
0       VU             23.3
1       FJ             29.2
2       WS             23.6
3       TO             14.8
4       KI             41.0
5       PG             57.3

In [6]:
agricultural_land_last_time

   GEO_PICT  agricultural_land Pacific Island Countries and territories
0        AS              14.05                           American Samoa
1        FJ              17.16                                     Fiji
2        FM               7.14         Micronesia (Federated States of)
3        GU              29.63                                     Guam
4        KI              41.98                                 Kiribati
5        MH              38.89                         Marshall Islands
6        MP               1.17                 Northern Mariana Islands
7        NC              10.07                            New Caledonia
8        NR              20.00                                    Nauru
9        PF              13.68                         French Polynesia
10       PG               3.10                         Papua New Guinea
11       PW               9.35                                    Palau
12       SB               4.29                          Solomon Islands
13       TO              48.61                                    Tonga
14       TV              60.00                                   Tuvalu
15       VU              15.34                                  Vanuatu
16       WS              19.85                                    Samoa

In [18]:
result = agricultural_land_last_time.merge(value_last_time, on='GEO_PICT',how='left') \
           .merge(employment_last_time, on='GEO_PICT',how='left')\
           .merge(food_security, on='GEO_PICT',how='left')\
           .merge(fishing, on='GEO_PICT',how='left')\
           
#Agricultural Land Efficiency Vulnerability Index (ALEVI)
result['ALEVI']=result['agriculture_value_added']/result['agricultural_land']
#Agricultural Employment Vulnerability Index (AEVI)
result['AEVI']=result['employment_agriculture']/result['agricultural_land']

result.to_csv('/Users/alexfion/Dropbox/Alex/dataViz/AShymanskaya.github.io/portfolio/visualizations/pacific_dataviz/full_story/data/alevi.csv')

In [19]:
result

,GEO_PICT,agricultural_land,Pacific Island Countries and territories,agriculture_value_added,employment_agriculture,food_insecurity,fishing_families,ALEVI,AEVI
0,AS,14.05,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN
1,FJ,17.16,Fiji,8.29,28.80,29.2,NaN,0.483100,1.678322
2,FM,7.14,Micronesia (Federated States of),22.47,NaN,NaN,NaN,3.147059,NaN
3,GU,29.63,Guam,NaN,0.24,NaN,NaN,NaN,0.008100
4,KI,41.98,Kiribati,23.09,NaN,41.0,44.0,0.550024,NaN
5,MH,38.89,Marshall Islands,20.63,NaN,NaN,15.0,0.530471,NaN
6,MP,1.17,Northern Mariana Islands,NaN,NaN,NaN,NaN,NaN,NaN
7,NC,10.07,New Caledonia,1.79,1.82,NaN,NaN,0.177756,0.180735
8,NR,20.00,Nauru,NaN,NaN,NaN,14.0,NaN,NaN
9,PF,13.68,French Polynesia,2.25,2.11,NaN,NaN,0.164474,0.154240
10,PG,3.10,Papua New Guinea,16.93,18.48,57.3,NaN,5.461290,5.961290
11,PW,9.35,Palau,3.41,NaN,NaN,10.0,0.364706,NaN
12,SB,4.29,Solomon Islands,33.76,37.29,NaN,NaN,7.869464,8.692308
13,TO,48.61,Tonga,16.32,26.94,14.8,10.0,0.335733,0.554207
14,TV,60.00,Tuvalu,NaN,NaN,NaN,53.0,NaN,NaN
15,VU,15.34,Vanuatu,21.22,42.35,23.3,31.0,1.383312,2.760756
16,WS,19.85,Samoa,11.02,20.14,23.6,NaN,0.555164,1.014610

In [10]:
food_insecure_counries=food_security.GEO_PICT.values

food_security[food_security.GEO_PICT.isin(food_insecure_counries)].food_insecurity.mean()

31.53333333333333

In [31]:
employments[employments['Indicator']=='Agriculture, value added (% of GDP)'][['TIME_PERIOD','OBS_VALUE','Pacific Island Countries and territories']].groupby('Pacific Island Countries and territories').last().mean()

TIME_PERIOD    2021.250000
OBS_VALUE        15.098333
dtype: float64